-- View: Araç detayları (join’leri UI’da yazmak yerine)
CREATE OR ALTER VIEW dbo.v_AracDetay
AS
SELECT
  A.SASE_NO,
  A.PLAKA,
  A.DURUM,
  A.KM,
  A.RENK,
  M.MODEL_ID,
  M.Marka,
  M.Seri,
  M.Model,
  M.Yil,
  M.GUNLUK_KIRA_BEDELI,
  S.SUBE_ID AS GUNCEL_SUBE_ID,
  S.SUBE_ADI AS GUNCEL_SUBE_ADI,
  S.IL, S.ILCE
FROM ARAC A
JOIN MODEL M ON A.MODEL_ID = M.MODEL_ID
JOIN SUBELER S ON A.GUNCEL_SUBE_ID = S.SUBE_ID;

GO

-- Müşteri Ekle
CREATE OR ALTER PROCEDURE dbo.sp_MusteriEkle
  @TC_NO VARCHAR(11),
  @EHLIYET_ID VARCHAR(20),
  @AD VARCHAR(100),
  @SOYAD VARCHAR(100),
  @TELEFON VARCHAR(15),
  @EMAIL VARCHAR(255)
AS
BEGIN
  SET NOCOUNT ON;
  INSERT INTO MUSTERILER (TC_NO, EHLIYET_ID, AD, SOYAD, TELEFON, [E-MAIL])
  VALUES (@TC_NO, @EHLIYET_ID, @AD, @SOYAD, @TELEFON, @EMAIL);
END
GO

-- Müşteri Güncelle (örnek alanlar)
CREATE OR ALTER PROCEDURE dbo.sp_MusteriGuncelle
  @MUSTERI_ID INT,
  @TELEFON VARCHAR(15),
  @EMAIL VARCHAR(255),
  @ADRES VARCHAR(500) = NULL
AS
BEGIN
  SET NOCOUNT ON;
  UPDATE MUSTERILER
    SET TELEFON = @TELEFON, [E-MAIL] = @EMAIL, ADRES = @ADRES
  WHERE MUSTERI_ID = @MUSTERI_ID;
END
GO

-- Müşteri Sil (yumuşak silme)
CREATE OR ALTER PROCEDURE dbo.sp_MusteriSilSoft
  @MUSTERI_ID INT
AS
BEGIN
  SET NOCOUNT ON;
  UPDATE MUSTERILER SET DURUM = 'Silindi' WHERE MUSTERI_ID = @MUSTERI_ID;
END
GO