USE ARACKIRALAMADB;
GO

/* Araç detayı (UI JOIN yazmasın) */
CREATE OR ALTER VIEW dbo.v_AracDetay
AS
SELECT
  A.SASE_NO,
  A.PLAKA,
  A.DURUM,
  A.KM,
  A.RENK,
  M.MODEL_ID,
  M.Marka,
  M.Seri,
  M.Model,
  M.Yil,
  M.GUNLUK_KIRA_BEDELI,
  M.DEPOZITO_UCRETI,
  S.SUBE_ID AS GUNCEL_SUBE_ID,
  S.SUBE_ADI AS GUNCEL_SUBE_ADI,
  S.IL, 
  S.ILCE
FROM dbo.ARAC AS A
JOIN dbo.MODEL AS M ON A.MODEL_ID = M.MODEL_ID
JOIN dbo.SUBELER AS S ON A.GUNCEL_SUBE_ID = S.SUBE_ID;
GO

/* Şube + Çalışan ile giriş (demo: TC_NO parola olarak kullanılıyor) */
CREATE OR ALTER PROCEDURE dbo.sp_LoginCalisan
  @SUBE_ID INT,
  @EMAIL VARCHAR(255),
  @TC_NO VARCHAR(11)
AS
BEGIN
  SET NOCOUNT ON;

  SELECT TOP 1 
    C.CALISAN_ID,
    C.SUBE_ID,
    S.SUBE_ADI,
    C.[E-MAIL] AS EMAIL,
    C.AD,
    C.SOYAD,
    C.POZISYON,
    C.DURUM
  FROM dbo.CALISANLAR C
  JOIN dbo.SUBELER S ON S.SUBE_ID = C.SUBE_ID
  WHERE C.SUBE_ID = @SUBE_ID
    AND C.[E-MAIL] = @EMAIL
    AND C.TC_NO = @TC_NO
    AND (C.DURUM IS NULL OR C.DURUM = 'Aktif');
END
GO

/* Şubeye göre araç listele + arama + sayfalama */
CREATE OR ALTER PROCEDURE dbo.sp_AracListeleBySube
  @SUBE_ID INT,
  @Q NVARCHAR(100) = NULL,
  @PAGE INT = 1,
  @PAGE_SIZE INT = 25
AS
BEGIN
  SET NOCOUNT ON;

  WITH F AS (
    SELECT *
    FROM dbo.v_AracDetay
    WHERE GUNCEL_SUBE_ID = @SUBE_ID
      AND (@Q IS NULL OR @Q = '' OR
          Marka LIKE '%' + @Q + '%' OR
          Model LIKE '%' + @Q + '%' OR
          PLAKA LIKE '%' + @Q + '%')
  )
  SELECT *
  FROM F
  ORDER BY Marka, Model, PLAKA
  OFFSET (@PAGE-1)*@PAGE_SIZE ROWS FETCH NEXT @PAGE_SIZE ROWS ONLY;
END
GO

/* Araç ekle */
CREATE OR ALTER PROCEDURE dbo.sp_AracEkle
  @SASE_NO VARCHAR(17),
  @MODEL_ID INT,
  @GUNCEL_SUBE_ID INT,
  @PLAKA VARCHAR(15),
  @KM INT,
  @DURUM VARCHAR(50),
  @RENK VARCHAR(50) = NULL
AS
BEGIN
  SET NOCOUNT ON;

  INSERT INTO dbo.ARAC (SASE_NO, MODEL_ID, GUNCEL_SUBE_ID, PLAKA, KM, DURUM, RENK)
  VALUES (@SASE_NO, @MODEL_ID, @GUNCEL_SUBE_ID, @PLAKA, @KM, @DURUM, @RENK);
END
GO

/* Araç güncelle */
CREATE OR ALTER PROCEDURE dbo.sp_AracGuncelle
  @SASE_NO VARCHAR(17),
  @MODEL_ID INT = NULL,
  @GUNCEL_SUBE_ID INT = NULL,
  @PLAKA VARCHAR(15) = NULL,
  @KM INT = NULL,
  @DURUM VARCHAR(50) = NULL,
  @RENK VARCHAR(50) = NULL
AS
BEGIN
  SET NOCOUNT ON;

  UPDATE dbo.ARAC
  SET MODEL_ID = COALESCE(@MODEL_ID, MODEL_ID),
      GUNCEL_SUBE_ID = COALESCE(@GUNCEL_SUBE_ID, GUNCEL_SUBE_ID),
      PLAKA = COALESCE(@PLAKA, PLAKA),
      KM = COALESCE(@KM, KM),
      DURUM = COALESCE(@DURUM, DURUM),
      RENK = COALESCE(@RENK, RENK)
  WHERE SASE_NO = @SASE_NO;
END
GO

/* Araç sil (referans varsa Pasif yapar; yoksa fiziksel siler) */
CREATE OR ALTER PROCEDURE dbo.sp_AracSilGuvenli
  @SASE_NO VARCHAR(17)
AS
BEGIN
  SET NOCOUNT ON;

  IF EXISTS (SELECT 1 FROM dbo.KIRALAMA WHERE SASE_NO = @SASE_NO)
     OR EXISTS (SELECT 1 FROM dbo.BAKIM_KAYITLARI WHERE SASE_NO = @SASE_NO)
     OR EXISTS (SELECT 1 FROM dbo.SIGORTA WHERE SASE_NO = @SASE_NO)
  BEGIN
    UPDATE dbo.ARAC SET DURUM = 'Pasif' WHERE SASE_NO = @SASE_NO;
    RETURN;
  END

  DELETE FROM dbo.ARAC WHERE SASE_NO = @SASE_NO;
END
GO

/* Model fiyat/depozito güncelle */
CREATE OR ALTER PROCEDURE dbo.sp_ModelFiyatGuncelle
  @MODEL_ID INT,
  @GUNLUK_KIRA_BEDELI DECIMAL(10,2),
  @DEPOZITO_UCRETI DECIMAL(10,2)
AS
BEGIN
  SET NOCOUNT ON;

  UPDATE dbo.MODEL
  SET GUNLUK_KIRA_BEDELI = @GUNLUK_KIRA_BEDELI,
      DEPOZITO_UCRETI = @DEPOZITO_UCRETI
  WHERE MODEL_ID = @MODEL_ID;
END
GO

/* Kampanyalar */
CREATE OR ALTER PROCEDURE dbo.sp_KampanyaListele
AS
BEGIN
  SET NOCOUNT ON;
  SELECT * FROM dbo.KAMPANYALAR ORDER BY AKTIF_MI DESC, BASLANGIC_TARIHI DESC;
END
GO

CREATE OR ALTER PROCEDURE dbo.sp_KampanyaEkle
  @KAMPANYA_ADI VARCHAR(255),
  @BASLANGIC_TARIHI DATE = NULL,
  @BITIS_TARIHI DATE = NULL,
  @INDIRIM_ORANI DECIMAL(5,2) = NULL,
  @KOSULLAR VARCHAR(1000) = NULL,
  @AKTIF_MI BIT = 1
AS
BEGIN
  SET NOCOUNT ON;
  INSERT INTO dbo.KAMPANYALAR (KAMPANYA_ADI, BASLANGIC_TARIHI, BITIS_TARIHI, INDIRIM_ORANI, KOSULLAR, AKTIF_MI)
  VALUES (@KAMPANYA_ADI, @BASLANGIC_TARIHI, @BITIS_TARIHI, @INDIRIM_ORANI, @KOSULLAR, @AKTIF_MI);
END
GO

CREATE OR ALTER PROCEDURE dbo.sp_KampanyaGuncelle
  @KAMPANYA_ID INT,
  @KAMPANYA_ADI VARCHAR(255) = NULL,
  @BASLANGIC_TARIHI DATE = NULL,
  @BITIS_TARIHI DATE = NULL,
  @INDIRIM_ORANI DECIMAL(5,2) = NULL,
  @KOSULLAR VARCHAR(1000) = NULL,
  @AKTIF_MI BIT = NULL
AS
BEGIN
  SET NOCOUNT ON;
  UPDATE dbo.KAMPANYALAR
  SET KAMPANYA_ADI = COALESCE(@KAMPANYA_ADI, KAMPANYA_ADI),
      BASLANGIC_TARIHI = COALESCE(@BASLANGIC_TARIHI, BASLANGIC_TARIHI),
      BITIS_TARIHI = COALESCE(@BITIS_TARIHI, BITIS_TARIHI),
      INDIRIM_ORANI = COALESCE(@INDIRIM_ORANI, INDIRIM_ORANI),
      KOSULLAR = COALESCE(@KOSULLAR, KOSULLAR),
      AKTIF_MI = COALESCE(@AKTIF_MI, AKTIF_MI)
  WHERE KAMPANYA_ID = @KAMPANYA_ID;
END
GO

CREATE OR ALTER PROCEDURE dbo.sp_KampanyaSil
  @KAMPANYA_ID INT
AS
BEGIN
  SET NOCOUNT ON;
  DELETE FROM dbo.KAMPANYALAR WHERE KAMPANYA_ID = @KAMPANYA_ID;
END
GO

/* Ek Hizmetler */
CREATE OR ALTER PROCEDURE dbo.sp_HizmetListele
AS
BEGIN
  SET NOCOUNT ON;
  SELECT * FROM dbo.EK_HIZMETLER ORDER BY HIZMET_ADI;
END
GO

CREATE OR ALTER PROCEDURE dbo.sp_HizmetEkle
  @HIZMET_ADI VARCHAR(150),
  @UCRET_TIPI VARCHAR(20),
  @UCRET DECIMAL(10,2)
AS
BEGIN
  SET NOCOUNT ON;
  INSERT INTO dbo.EK_HIZMETLER (HIZMET_ADI, UCRET_TIPI, UCRET)
  VALUES (@HIZMET_ADI, @UCRET_TIPI, @UCRET);
END
GO

CREATE OR ALTER PROCEDURE dbo.sp_HizmetGuncelle
  @HIZMET_ID INT,
  @HIZMET_ADI VARCHAR(150) = NULL,
  @UCRET_TIPI VARCHAR(20) = NULL,
  @UCRET DECIMAL(10,2) = NULL
AS
BEGIN
  SET NOCOUNT ON;
  UPDATE dbo.EK_HIZMETLER
  SET HIZMET_ADI = COALESCE(@HIZMET_ADI, HIZMET_ADI),
      UCRET_TIPI = COALESCE(@UCRET_TIPI, UCRET_TIPI),
      UCRET = COALESCE(@UCRET, UCRET)
  WHERE HIZMET_ID = @HIZMET_ID;
END
GO

CREATE OR ALTER PROCEDURE dbo.sp_HizmetSil
  @HIZMET_ID INT
AS
BEGIN
  SET NOCOUNT ON;
  DELETE FROM dbo.EK_HIZMETLER WHERE HIZMET_ID = @HIZMET_ID;
END
GO