USE ARACKIRALAMADB;
GO
CREATE OR ALTER PROCEDURE dbo.sp_LoginCalisan
  @SUBE_ID INT,
  @CALISAN_ID INT
AS
BEGIN
  SET NOCOUNT ON;

  SELECT TOP 1 
    C.CALISAN_ID,
    C.SUBE_ID,
    S.SUBE_ADI,
    C.[E-MAIL] AS EMAIL,
    C.AD,
    C.SOYAD,
    C.POZISYON,
    C.DURUM
  FROM dbo.CALISANLAR C
  JOIN dbo.SUBELER S ON S.SUBE_ID = C.SUBE_ID
  WHERE C.SUBE_ID = @SUBE_ID
    AND C.CALISAN_ID = @CALISAN_ID
    AND (C.DURUM IS NULL OR C.DURUM = 'Aktif');
END
GO